/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectFamilyRouteImport } from './routes/select-family'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as CreateFamilyRouteImport } from './routes/create-family'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeSettingsRouteImport } from './routes/home/settings'
import { Route as HomeKidsRouteImport } from './routes/home/kids'
import { Route as HomeChoresRouteRouteImport } from './routes/home/chores/route'
import { Route as HomeChoresIndexRouteImport } from './routes/home/chores/index'
import { Route as HomeChoresPendingRouteImport } from './routes/home/chores/pending'
import { Route as HomeChoresLibraryRouteImport } from './routes/home/chores/library'
import { Route as HomeChoresCompletedRouteImport } from './routes/home/chores/completed'
import { Route as HomeChoresActiveRouteImport } from './routes/home/chores/active'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectFamilyRoute = SelectFamilyRouteImport.update({
  id: '/select-family',
  path: '/select-family',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFamilyRoute = CreateFamilyRouteImport.update({
  id: '/create-family',
  path: '/create-family',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeKidsRoute = HomeKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeChoresRouteRoute = HomeChoresRouteRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeChoresIndexRoute = HomeChoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeChoresRouteRoute,
} as any)
const HomeChoresPendingRoute = HomeChoresPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => HomeChoresRouteRoute,
} as any)
const HomeChoresLibraryRoute = HomeChoresLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => HomeChoresRouteRoute,
} as any)
const HomeChoresCompletedRoute = HomeChoresCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => HomeChoresRouteRoute,
} as any)
const HomeChoresActiveRoute = HomeChoresActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => HomeChoresRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/chores': typeof HomeChoresRouteRouteWithChildren
  '/home/kids': typeof HomeKidsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
  '/home/chores/active': typeof HomeChoresActiveRoute
  '/home/chores/completed': typeof HomeChoresCompletedRoute
  '/home/chores/library': typeof HomeChoresLibraryRoute
  '/home/chores/pending': typeof HomeChoresPendingRoute
  '/home/chores/': typeof HomeChoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/kids': typeof HomeKidsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home': typeof HomeIndexRoute
  '/home/chores/active': typeof HomeChoresActiveRoute
  '/home/chores/completed': typeof HomeChoresCompletedRoute
  '/home/chores/library': typeof HomeChoresLibraryRoute
  '/home/chores/pending': typeof HomeChoresPendingRoute
  '/home/chores': typeof HomeChoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/chores': typeof HomeChoresRouteRouteWithChildren
  '/home/kids': typeof HomeKidsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
  '/home/chores/active': typeof HomeChoresActiveRoute
  '/home/chores/completed': typeof HomeChoresCompletedRoute
  '/home/chores/library': typeof HomeChoresLibraryRoute
  '/home/chores/pending': typeof HomeChoresPendingRoute
  '/home/chores/': typeof HomeChoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/chores'
    | '/home/kids'
    | '/home/settings'
    | '/home/'
    | '/home/chores/active'
    | '/home/chores/completed'
    | '/home/chores/library'
    | '/home/chores/pending'
    | '/home/chores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/kids'
    | '/home/settings'
    | '/home'
    | '/home/chores/active'
    | '/home/chores/completed'
    | '/home/chores/library'
    | '/home/chores/pending'
    | '/home/chores'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/chores'
    | '/home/kids'
    | '/home/settings'
    | '/home/'
    | '/home/chores/active'
    | '/home/chores/completed'
    | '/home/chores/library'
    | '/home/chores/pending'
    | '/home/chores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  CreateFamilyRoute: typeof CreateFamilyRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  SelectFamilyRoute: typeof SelectFamilyRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-family': {
      id: '/select-family'
      path: '/select-family'
      fullPath: '/select-family'
      preLoaderRoute: typeof SelectFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-family': {
      id: '/create-family'
      path: '/create-family'
      fullPath: '/create-family'
      preLoaderRoute: typeof CreateFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/kids': {
      id: '/home/kids'
      path: '/kids'
      fullPath: '/home/kids'
      preLoaderRoute: typeof HomeKidsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/chores': {
      id: '/home/chores'
      path: '/chores'
      fullPath: '/home/chores'
      preLoaderRoute: typeof HomeChoresRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/chores/': {
      id: '/home/chores/'
      path: '/'
      fullPath: '/home/chores/'
      preLoaderRoute: typeof HomeChoresIndexRouteImport
      parentRoute: typeof HomeChoresRouteRoute
    }
    '/home/chores/pending': {
      id: '/home/chores/pending'
      path: '/pending'
      fullPath: '/home/chores/pending'
      preLoaderRoute: typeof HomeChoresPendingRouteImport
      parentRoute: typeof HomeChoresRouteRoute
    }
    '/home/chores/library': {
      id: '/home/chores/library'
      path: '/library'
      fullPath: '/home/chores/library'
      preLoaderRoute: typeof HomeChoresLibraryRouteImport
      parentRoute: typeof HomeChoresRouteRoute
    }
    '/home/chores/completed': {
      id: '/home/chores/completed'
      path: '/completed'
      fullPath: '/home/chores/completed'
      preLoaderRoute: typeof HomeChoresCompletedRouteImport
      parentRoute: typeof HomeChoresRouteRoute
    }
    '/home/chores/active': {
      id: '/home/chores/active'
      path: '/active'
      fullPath: '/home/chores/active'
      preLoaderRoute: typeof HomeChoresActiveRouteImport
      parentRoute: typeof HomeChoresRouteRoute
    }
  }
}

interface HomeChoresRouteRouteChildren {
  HomeChoresActiveRoute: typeof HomeChoresActiveRoute
  HomeChoresCompletedRoute: typeof HomeChoresCompletedRoute
  HomeChoresLibraryRoute: typeof HomeChoresLibraryRoute
  HomeChoresPendingRoute: typeof HomeChoresPendingRoute
  HomeChoresIndexRoute: typeof HomeChoresIndexRoute
}

const HomeChoresRouteRouteChildren: HomeChoresRouteRouteChildren = {
  HomeChoresActiveRoute: HomeChoresActiveRoute,
  HomeChoresCompletedRoute: HomeChoresCompletedRoute,
  HomeChoresLibraryRoute: HomeChoresLibraryRoute,
  HomeChoresPendingRoute: HomeChoresPendingRoute,
  HomeChoresIndexRoute: HomeChoresIndexRoute,
}

const HomeChoresRouteRouteWithChildren = HomeChoresRouteRoute._addFileChildren(
  HomeChoresRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeChoresRouteRoute: typeof HomeChoresRouteRouteWithChildren
  HomeKidsRoute: typeof HomeKidsRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeChoresRouteRoute: HomeChoresRouteRouteWithChildren,
  HomeKidsRoute: HomeKidsRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  CreateFamilyRoute: CreateFamilyRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  SelectFamilyRoute: SelectFamilyRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
