/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectFamilyRouteImport } from './routes/select-family'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as CreateFamilyRouteImport } from './routes/create-family'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeUsersRouteImport } from './routes/home/users'
import { Route as HomeSettingsRouteImport } from './routes/home/settings'
import { Route as HomeLibraryRouteImport } from './routes/home/library'
import { Route as HomeKidsRouteImport } from './routes/home/kids'
import { Route as HomeChoresRouteImport } from './routes/home/chores'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectFamilyRoute = SelectFamilyRouteImport.update({
  id: '/select-family',
  path: '/select-family',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFamilyRoute = CreateFamilyRouteImport.update({
  id: '/create-family',
  path: '/create-family',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUsersRoute = HomeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLibraryRoute = HomeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeKidsRoute = HomeKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeChoresRoute = HomeChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/chores': typeof HomeChoresRoute
  '/home/kids': typeof HomeKidsRoute
  '/home/library': typeof HomeLibraryRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/users': typeof HomeUsersRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/chores': typeof HomeChoresRoute
  '/home/kids': typeof HomeKidsRoute
  '/home/library': typeof HomeLibraryRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/users': typeof HomeUsersRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/create-family': typeof CreateFamilyRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/select-family': typeof SelectFamilyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/home/chores': typeof HomeChoresRoute
  '/home/kids': typeof HomeKidsRoute
  '/home/library': typeof HomeLibraryRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/users': typeof HomeUsersRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/chores'
    | '/home/kids'
    | '/home/library'
    | '/home/settings'
    | '/home/users'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/chores'
    | '/home/kids'
    | '/home/library'
    | '/home/settings'
    | '/home/users'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/create-family'
    | '/kiosk'
    | '/login'
    | '/select-family'
    | '/signup'
    | '/verify-email'
    | '/home/chores'
    | '/home/kids'
    | '/home/library'
    | '/home/settings'
    | '/home/users'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  CreateFamilyRoute: typeof CreateFamilyRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  SelectFamilyRoute: typeof SelectFamilyRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-family': {
      id: '/select-family'
      path: '/select-family'
      fullPath: '/select-family'
      preLoaderRoute: typeof SelectFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-family': {
      id: '/create-family'
      path: '/create-family'
      fullPath: '/create-family'
      preLoaderRoute: typeof CreateFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/users': {
      id: '/home/users'
      path: '/users'
      fullPath: '/home/users'
      preLoaderRoute: typeof HomeUsersRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/library': {
      id: '/home/library'
      path: '/library'
      fullPath: '/home/library'
      preLoaderRoute: typeof HomeLibraryRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/kids': {
      id: '/home/kids'
      path: '/kids'
      fullPath: '/home/kids'
      preLoaderRoute: typeof HomeKidsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/chores': {
      id: '/home/chores'
      path: '/chores'
      fullPath: '/home/chores'
      preLoaderRoute: typeof HomeChoresRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeChoresRoute: typeof HomeChoresRoute
  HomeKidsRoute: typeof HomeKidsRoute
  HomeLibraryRoute: typeof HomeLibraryRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeUsersRoute: typeof HomeUsersRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeChoresRoute: HomeChoresRoute,
  HomeKidsRoute: HomeKidsRoute,
  HomeLibraryRoute: HomeLibraryRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeUsersRoute: HomeUsersRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  CreateFamilyRoute: CreateFamilyRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  SelectFamilyRoute: SelectFamilyRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
